const blog = {
  actions: {
     RETRIEVE_BLOG_REQUEST : 'dealty/plan/RETRIEVE_BLOG_REQUEST',
     RETRIEVE_BLOG_SUCCESS : 'dealty/plan/RETRIEVE_BLOG_SUCCESS',
     RETRIEVE_BLOG_FAILURE : 'dealty/plan/RETRIEVE_BLOG_FAILURE',

     RETRIEVE_BLOGS_REQUEST : 'dealty/blogs/RETRIEVE_BLOGS_REQUEST',
     RETRIEVE_BLOGS_SUCCESS : 'dealty/blogs/RETRIEVE_BLOGS_SUCCESS',
     RETRIEVE_BLOGS_FAILURE : 'dealty/blogs/RETRIEVE_BLOGS_FAILURE',

     RETRIEVE_MOST_LATEST_BLOG_REQUEST : 'dealty/plan/RETRIEVE__MOST_LATEST_BLOG_REQUEST',
     RETRIEVE_MOST_LATEST_BLOG_SUCCESS : 'dealty/plan/RETRIEVE_MOST_LATEST_BLOG_SUCCESS',
     RETRIEVE_MOST_LATEST_BLOG_FAILURE : 'dealty/plan/RETRIEVE_MOST_LATEST_BLOG_FAILURE',

     RETRIEVE_RANDOM_BLOGS_REQUEST : 'dealty/blogs/RETRIEVE_RANDOM_BLOGS_REQUEST',
     RETRIEVE_RANDOM_BLOGS_SUCCESS : 'dealty/blogs/RETRIEVE_RANDOM_BLOGS_SUCCESS',
     RETRIEVE_RANDOM_BLOGS_FAILURE : 'dealty/blogs/RETRIEVE_RANDOM_BLOGS_FAILURE',
  },
}
export default blog